---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: api-keys
  namespace: default
spec:
  encryptedData:
    APIKEY: AgC6Qc+FOysqO/yzSFu6PBZo2OA423CIZJwEN5qAO5QdYnVV28PYLdcBWmq8F6wYJsL8knuU8AeGU1D6CGKCU4Vd/RWFPKRZYi9GIXZN/pL5C++YiPswykGLJuen7WHpN5W+LLlBD7QytPmbe1H6qmZe1QPuMqngEY2icZKeWiYxdfaycNVvSb0NQFjFaqzDUNaWF084cuN7OMley2KPTzRjougYTRHB6hpyobrD2AcoG8IqVwXzLmp4tYD5zYl0yWavmNYYIlMk3zls6sZ4SPz0igRjO6sQbLX/hHOBzDXDZ4ybyemR9GYzQbJQGCGgCEhoHNe3Nk3aALxmFqpDWSVzx2ctx5B4INdxp5jVplqnjKj9IfzqFYygagPSj+DEbWm5Ij3itVtnyM1Q0asgYpUsD+xT0TC7JsFj4I8rJTTyvzz4T5ErdNP6/6tACVX7lnx2kKFxeDyUTgcCBrsTgH0yrvBt0CWKc7CSvbkmi/9bouyS9wUBn8BTwwtCJ4tmOk2UZHoCAtq15BiHk/MjqJRke6Hcm3dytLQ0iiIvTChanYurLb6t//PkMjCcdey2XLbwy4oRwy7pkOYS5VZQ2eckYXvKMzR31DedkKXtXVjduOUkz7jBIzwMPA9c+Vv0TaGyKU2a9wYMPfzyQ5s83fFhpEFALKE86IsKP5NF0EA8qyKtiOjY1AFlu3Y5yFh4zXgO33xTpUo3N8k2LddN9YB+gGlYFNxxgeINrhYp1HtuhQQ6LknWyzSP/tBKmYp/PILc42s=
  template:
    metadata:
      creationTimestamp: null
      name: api-keys
      namespace: default
    type: Opaque
