apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: api-keys
  namespace: default
spec:
  encryptedData:
    APIKEY: AgB9dBwS+9TkbwyyXK5C0RyEcH21m7Hul0IHFRmK7BKpRVjKKF0gUhNr+fbZXfw9360+1KUW0NaFhN7HvUX6Tli1Eq76WdF+FIOE5oVDgL0/BNc9FoGmFXV3x0BRBPJro9oLNQQWrIlLKOl/yJiu3XYHyZqIQBMiQqrkxZvypnJK/vQdjYz+iY42CSITwwBanpbV+MUXLxs73DZHfm7iEQd9M8ygJaW8rCqiJNl3iv670p423nGAuQ+m6sv0Zt8bLKCG3nPrvlMJcYc+ukaU18IhN6sJg3AFrwsGwwBBaP/C55llNtnyGgBTMpYSORIWZT+2wFzFWqgX58WgWr424rFNNHbA/nXl+S5SVpxYHpbfxgu1qUJe37nGEngeTJemiyfbtNB2klXw6zOaF18A96C6/1BMllXarxrPtMJxh7S4m1ks/yfCcivZu2qgYKQfQx9fH/2+zy0oo+cNoNPH7S6xOiLJQDJC9Y0SgEzPkhXHZcz47s9SEa8o0NeIZRVwUvuxmPXhCS3M29ICewbL9INXBu2VNA5w0JHxLd4yGyKBF/zNH+hxLm1fr8qldORJ8GstaT1HAcNvuT3coP6+gjuXd6WlqcDF3pmD28+VbyTA+x3NUV41Ca34Pspady6gEXAAUcxmxG1osvXxCtyBSNsaeyf+YMLt3IZbKHyC1b+L+XS/p93rc32iMf/w7q+tpJ2WuHeLM74VY9wRkpnyM4yGYxWQedrT2g4RnA4nn0HcSr0Mr7scGAlvbPmwL4QSsZ29iWw=
  template:
    metadata:
      creationTimestamp: null
      name: api-keys
      namespace: default
    type: Opaque
